tracer/urls.py
from django.conf.urls import url
from django.contrib import admin
from app01 import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app01/sendcode/', views.send_code),
    url(r'^app01/register/', views.register),
]

web/urls.py
from django.conf.urls import url
from web.views import account, home, project

urlpatterns = [
    url(r'^register/$', account.register, name='register'),
    url(r'^login/code/$', account.login_code, name='login_code'),
    url(r'^login/$', account.login, name='login'),
    url(r'^send/code/$', account.send_code, name='send_code'),
    url(r'^image/code/$', account.image_code, name='image_code'),
    url(r'^index/$', home.index, name='index'),
    url(r'^logout/$', account.logout, name='logout'),
    # 项目管理
    url(r'^project/list/$', project.project_list, name='project_list'),
    url(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_star, name='project_star'),
    url(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_unstar, name='project_unstar'),

]

web/models.py
from django.db import models

class UserInfo(models.Model):
    username = models.CharField(verbose_name="用户名", max_length=32, db_index=True)  # db_index=True可以创建索引，查询速度快
    password = models.CharField(verbose_name="密码", max_length=32)
    email = models.EmailField(verbose_name="邮箱", max_length=32)

class PriceStrategy(models.Model):
    '''价格策略表'''
    category_choice = (
        (1, '免费版'),
        (2, '收费版'),
        (3, '其他')
    )
    category = models.SmallIntegerField(verbose_name='收费类型',default=1, choices=category_choice)
    title = models.CharField(verbose_name='标题', max_length=32)
    price = models.PositiveIntegerField(verbose_name='价格')
    project_num = models.PositiveIntegerField(verbose_name='项目数')
    project_member = models.PositiveIntegerField(verbose_name='项目成员数')
    project_space = models.PositiveIntegerField(verbose_name='单项目空间')
    per_file_size = models.PositiveIntegerField(verbose_name='单文件大小')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

class TradeInfo(models.Model):
    '''用户订单表'''
    oid = models.CharField(verbose_name='交易订单', max_length=128, unique=True)
    status_choice = (
        (1, '未支付'),
        (2, '已支付')
    )
    status = models.SmallIntegerField(verbose_name='支付状态', choices=status_choice)
    user = models.ForeignKey(verbose_name='用户', to='UserInfo')
    price_strategy = models.ForeignKey(verbose_name='价格策略', to='PriceStrategy')
    count = models.SmallIntegerField(verbose_name='数量', help_text='0表示无期限')
    pay = models.IntegerField(verbose_name='实际支付价格')
    start_time = models.DateTimeField(verbose_name='开始时间', null=True, blank=True)
    end_time = models.DateTimeField(verbose_name='结束时间', null=True, blank=True)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

class ProjectInfo(models.Model):
    '''项目表'''
    name = models.CharField(verbose_name='项目名称', max_length=32)
    color_choice = (
        (1, '#56b8eb'),
        (2, '#f28033'),
        (3, '#ebc656'),
        (4, '#a2d148'),
        (5, '#20BFA4'),
        (6, '#7461c2'),
        (7, '#20bfa3')
    )
    color = models.SmallIntegerField(verbose_name='项目颜色', choices=color_choice, default=1)
    detail = models.CharField(verbose_name='项目描述', max_length=255, null=True, blank=True)
    use_space = models.IntegerField(verbose_name='项目已使用空间', default=0)
    star = models.BooleanField(verbose_name='星标', default=False)
    join_count = models.IntegerField(verbose_name='参与人数', default=1)
    creator = models.ForeignKey(verbose_name='创建人', to='UserInfo')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

class ProjectTeamInfo(models.Model):
    '''项目成员表'''
    user = models.ForeignKey(verbose_name='参与成员', to='UserInfo')
    project = models.ForeignKey(verbose_name='项目', to='ProjectInfo')
    star = models.BooleanField(verbose_name='星标', default=False)
    create_datetime = models.DateTimeField(verbose_name='加入时间', auto_now_add=True)

web/templates/index.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %}首页{% endblock %}
{% block css %}
    <style>
        img {
            width: 100%;
        }
    </style>
{% endblock %}

{% block content %}
    <div>
        <img src="{% static 'img/index/index-1.png' %}" alt="">
        <img src="{% static 'img/index/index-2.png' %}" alt="">
        <img src="{% static 'img/index/index-3.png' %}" alt="">
        <img src="{% static 'img/index/index-4.png' %}" alt="">
    </div>
{% endblock %}

web/templates/login.html
{% extends "layout/basic.html" %}
{% load static %}
{% block title %}
    用户登录
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .account .error-msg {
            color: red;
            font-size: 12px;
            position: absolute;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="account">
        <div class="title">用户登录</div>
        <form id="login_form" method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row clearfix">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg">{{ field.errors.0 }}</span>
                            </div>
                            <div class="col-xs-5">
                                <img src="/image/code/" id="imageCode" title="点击更换图片">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg">{{ field.errors.0 }}</span>
                    </div>
                {% endif %}
            {% endfor %}

            <input id="btnSubmit" type="submit" class="btn btn-primary" value="登  录">
        <div style="float: right;margin-top: 5px">
            <a href="{% url 'login_code' %}">邮箱验证码登录？</a>
        </div>
        </form>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $(function () {
            $("#imageCode").click(function () {
                var oldSrc = $(this).attr('src')
                $(this).attr('src', oldSrc + "?")
            })
        })

    </script>
{% endblock %}

web/templates/login_code.html
{% extends "layout/basic.html" %}
{% load static %}
{% block title %}
    邮箱登录
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .account .error-msg {
            color: red;
            font-size: 12px;
            position: absolute;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="account">
        <div class="title">邮箱登录</div>
        <form id="login_form" method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row clearfix">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg">{{ field.errors.0 }}</span>
                            </div>
                            <div class="col-xs-5">
                                <input style="width: 100%" type="buttom" id="code_button" class="btn btn-default"
                                       value="点击获取验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg">{{ field.errors.0 }}</span>
                    </div>
                {% endif %}
            {% endfor %}

            <input id="btnSubmit" type="button" class="btn btn-primary" value="登  录">
        <div style="float: right;margin-top: 5px">
            <a href="{% url 'login' %}">用户名密码登录？</a>
        </div>
        </form>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $(function () {
            bindSendCode();
            bindClickSubmit();
        })

        /*绑定发送验证码事件*/
        function bindSendCode() {
            $('#code_button').click(function () {
                $(".error-msg").empty()
                //获取邮箱
                var email = $('#id_email').val()  //modelform会生成id_+name的属性
                $.ajax({
                    url: "{% url 'send_code' %}",  //反向解析URL 等价于 /send/code/
                    type: 'GET',
                    data: {email: email, type: 'login'},
                    datatype: 'JSON',
                    success: function (res) {
                        if (res.status) {
                            console.log('发送成功')
                            codeClock()
                        } else {
                            $.each(res.error, function (name, error_lst) {
                                console.log(res)   //{"status": false,"error": {"email": ["输入一个有效的 Email 地址。"]}}
                                $("#id_" + name).next().text(error_lst[0]);
                            })
                        }
                    }
                })
            })
        }

        /*绑定倒计时事件*/
        function codeClock() {
            var codeButton = $("#code_button");
            codeButton.prop('disabled', true); //禁用
            var time = 60;
            var remind = setInterval(function () {
                codeButton.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind);
                    codeButton.val('点击获取验证码').prop('disabled', false)
                }
            }, 1000)
        }

        /*注册提交*/
        function bindClickSubmit() {
            $("#btnSubmit").click(function () {
                $(".error-msg").empty()
                //收集数据,发送到后台
                $.ajax({
                    url:"{% url 'login_code' %}",  //等价于/login/code/
                    type:"POST",
                    data:$("#login_form").serialize(),
                    datatype:'JSON',
                    success:function (res) {
                        if(res.status){
                            location.href = res.data  //跳转到了/login/
                        }else{
                            $.each(res.error, function (name, error_lst) {
                                console.log(res)   //{"status": false,"error": {"email": ["输入一个有效的 Email 地址。"]}}
                                $("#id_" + name).next().text(error_lst[0]);
                            })
                        }
                    }
                })
            })
        }
    </script>
{% endblock %}

web/templates/project_list.html
{% extends 'layout/manage.html' %}
{% block css %}
    <style>
        .project {
            margin-top: 10px;
        }

        .panel-body {
            padding: 0;
            display: flex;
            flex-direction: row;
            justify-content: left;
            align-items: flex-start;
            flex-wrap: wrap;
        }

        .panel-body > .item {
            border-radius: 6px;
            width: 228px;
            border: 1px solid #dddddd;
            margin: 20px 10px;

        }

        .panel-body > .item:hover {
            border: 1px solid #f0ad4e;
        }

        .panel-body > .item > .title {
            height: 104px;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            border-top-left-radius: 6px;
            border-top-right-radius: 6px;
            font-size: 15px;
            text-decoration: none;
        }

        .panel-body > .item > .info {
            padding: 10px 10px;

            display: flex;
            justify-content: space-between;

            border-bottom-left-radius: 6px;
            border-bottom-right-radius: 6px;
            color: #8c8c8c;

        }

        .panel-body > .item > .info a {
            text-decoration: none;
        }

        .panel-body > .item > .info .fa-star {
            font-size: 18px;
        }

        .color-radio label {
            margin-left: 0;
            padding-left: 0;
        }

        .color-radio input[type="radio"] {
            display: none;
        }

        .color-radio input[type="radio"] + .cycle {
            display: inline-block;
            height: 25px;
            width: 25px;
            border-radius: 50%;
            border: 2px solid #dddddd;
        }

        .color-radio input[type="radio"]:checked + .cycle {
            border: 2px solid black;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container-fluid project">
        <a class="btn btn-primary" data-toggle="modal" data-target="#addModal">
            <i class="fa fa-plus-circle" aria-hidden="true"></i> 新建项目
        </a>
        <div class="panel panel-default" style="margin-top: 10px">
            <div class="panel-heading"><i class="fa fa-star" aria-hidden="true"></i>星标项目</div>
            <div class="panel-body">
                {% for item in project_dict.star %}
                    <div class="item">
                        <a href="#" class="title"
                           style="background-color: {{ item.value.get_color_display }};">{{ item.value.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_unstar' project_type=item.type project_id=item.value.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #f0ad4e;"></i>
                                </a>
                                <span>{{ item.value.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.value.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-list" aria-hidden="true"></i>我创建的项目</div>
            <div class="panel-body">
                {% for item in project_dict.my %}
                    <div class="item">
                        <a href="#" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_star' project_type='my' project_id=item.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5;"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-handshake-o" aria-hidden="true"></i>我参与的项目</div>
            <div class="panel-body">
                {% for item in project_dict.join %}
                    <div class="item">
                        <a href="#" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_star' project_type='join' project_id=item.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5;"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建项目</h4>
                </div>
                <div class="modal-body">
                    <form id="addForm">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                        {% endfor %}
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button id="btnSubmit" type="button" class="btn btn-primary">保存</button>
                </div>
            </div>
        </div>
    </div>


{% endblock %}
{% block js %}
    <script type="text/javascript">
        $(function () {
            bindSubmit();
        });

        function bindSubmit() {
            $("#btnSubmit").click(function () {
                $(".error-msg").empty()
                $.ajax({
                    url: "{% url 'project_list' %}",
                    type: "POST",
                    data: $("#addForm").serialize(),
                    datatype: 'JSON',
                    success: function (res) {
                        if (res.status) {
                            location.reload()
                        } else {
                            $.each(res.error, function (name, error_lst) {
                                $("#id_" + name).next().text(error_lst[0]);
                            })
                        }
                    }
                })
            })
        }

    </script>
{% endblock %}

web/templates/register.html
{% extends "layout/basic.html" %}
{% load static %}
{% block title %}

{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .account .error-msg {
            color: red;
            font-size: 12px;
            position: absolute;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="account">
        <div class="title">{{ title }}</div>
        <form id="rg_form" method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row clearfix">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg">{{ field.errors.0 }}</span>
                            </div>
                            <div class="col-xs-5">
                                <input style="width: 100%" type="buttom" id="code_button" class="btn btn-default"
                                       value="点击获取验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg">{{ field.errors.0 }}</span>
                    </div>
                {% endif %}
            {% endfor %}

            <input id="btnSubmit" type="button" class="btn btn-primary" value="注  册">
        </form>
    </div>

{% endblock %}
{% block js %}
    <script type="text/javascript">
        $(function () {
            bindSendCode();
            bindClickSubmit();
        })

        /*绑定发送验证码事件*/
        function bindSendCode() {
            $('#code_button').click(function () {
                $(".error-msg").empty()
                //获取邮箱
                var email = $('#id_email').val()  //modelform会生成id_+name的属性
                $.ajax({
                    url: "{% url 'send_code' %}",  //反向解析URL 等价于 /send/code/
                    type: 'GET',
                    data: {email: email, type: 'register'},
                    datatype: 'JSON',
                    success: function (res) {
                        if (res.status) {
                            console.log('发送成功')
                            codeClock()
                        } else {
                            $.each(res.error, function (name, error_lst) {
                                console.log(res)   //{"status": false,"error": {"email": ["输入一个有效的 Email 地址。"]}}
                                $("#id_" + name).next().text(error_lst[0]);
                            })
                        }
                    }
                })
            })
        }

        /*绑定倒计时事件*/
        function codeClock() {
            var codeButton = $("#code_button");
            codeButton.prop('disabled', true); //禁用
            var time = 60;
            var remind = setInterval(function () {
                codeButton.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind);
                    codeButton.val('点击获取验证码').prop('disabled', false)
                }
            }, 1000)
        }

        /*注册提交*/
        function bindClickSubmit() {
            $("#btnSubmit").click(function () {
                $(".error-msg").empty()
                //收集数据,发送到后台
                $.ajax({
                    url:"{% url 'register' %}",
                    type:"POST",
                    data:$("#rg_form").serialize(),
                    datatype:'JSON',
                    success:function (res) {
                        if(res.status){
                            location.href = res.data  //跳转到了/login/
                        }else{
                            $.each(res.error, function (name, error_lst) {
                                console.log(res)   //{"status": false,"error": {"email": ["输入一个有效的 Email 地址。"]}}
                                $("#id_" + name).next().text(error_lst[0]);
                            })
                        }
                    }
                })
            })
        }
    </script>
{% endblock %}